version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:11.0.0
    working_directory: ~/liver-collection

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/liver-collection

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      - run: node -v
      - run: npm -v
      - run: npm install
      - run:
          command: |
            set +eo
            npm ls
            true
      - persist_to_workspace:
          root: ~/liver-collection
          paths:
            - node_modules
  build:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build

workflows:
  version: 2
  build:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - setup
